### ISSUE TITLE
Feature Request: Configuration Report

### ISSUE THREAD

**Issue by jmrieger** [splitio/split-synchronizer#134]
As a user of Split Synchronizer
I would like a panel on the Admin Dashboard that reflects the current configuration values the Synchronizer is running with
So that I may be confident that runtime configuration is being properly passed to the Synchronizer
  and so that I may know current configuration to determine how to tune the application in a production setting that may be experiencing performance issues.

**Comment by chillaq** [comment]
Hi @jmrieger , thanks for the info, I will submit a feature request on your behalf, we usually associate FR with company names, would you mind providing which company you work for?

Thanks
Bilal

**Comment by jmrieger** [comment]
> Hi @jmrieger , thanks for the info, I will submit a feature request on your behalf, we usually associate FR with company names, would you mind providing which company you work for?
> 
> Thanks
> Bilal

Certainly, Bilal! I work for Rocket Mortgage (Quicken Loans).

**Comment by chillaq** [comment]
Great, FR is submitted.
