### ISSUE TITLE
Error decoding event JSON invalid character

### ISSUE THREAD

**Issue by rtfarte** [splitio/split-synchronizer#142]
Running the split synchronizer using docker in a kubernetes cluster. After some time running the service, we get a number of logs showing the following error message:
```
split-synchronizer-preprod-7b8d94966-c2sk5 split-synchronizer SPLITIO-AGENT  - ERROR - 2021/09/01 16:48:46 impressions.go:142: Error decoding event JSON invalid character 'a' looking for beginning of value
```
Unfortunately, we don't have much of an idea why this error happens or how to fix it.

Split Sync version 4.0.2

**Comment by chillaq** [comment]
Hi @rtfarte , could you please provide the first 4 characters of the API Key used for the Synchronizer?

Thanks
Bilal

**Comment by rtfarte** [comment]
o as in octopus :)

**Comment by chillaq** [comment]
I cannot find an API Key containing these characters, what is your org name?

**Comment by rtfarte** [comment]
are you able to find anything with this dev API key: `gvlp`?

**Comment by ikubicki** [comment]
@chillaq any news on this?

**Comment by chillaq** [comment]
Hi @ikubicki , no updates yet, will check with the team.

**Comment by mmelograno** [comment]
Hi. @rtfarte  It has been a while since we heard back from you.
I'm closing out this ticket. If there's still an open issue or if we can be of further assistance on this topic, feel free to respond to this thread and the ticket will be re-opened.

Thanks,
Matias
