### ISSUE TITLE
Please release 4.0.3 to docker hub

### ISSUE THREAD

**Issue by rmelick-vida** [splitio/split-synchronizer#146]
I believe that the current `latest` tag on docker hub may be the 4.0.3 image, but there is no 4.0.3 tag.  I would like to be able to use 4.0.3 without using the `latest` tag, since `latest` could change without warning with future releases.

**Comment by chillaq** [comment]
Hi @rmelick-vida , As far as I remember we always use "latest" tag for last version, I understand your concern, will check with the team and get back to you.
