### ISSUE TITLE
impressionsPostRate cannot be reduced

### ISSUE THREAD

**Issue by rmelick-vida** [splitio/split-synchronizer#147]
The [Runbook](https://help.split.io/hc/en-us/articles/360018343391-Split-Synchronizer-Runbook) seems to say that one solution for improving impressions throughput is to decrease the `impressionsPostRate`

In Example 2 and 3, they give examples of decreasing the rate to 30 seconds or 15 seconds.

However, when attempting to configure it to 30 seconds, I get the following error:
```
Split Synchronizer - Initialization error: ImpressionsPostRate must be >= 60. Actual is: 30
```

Seems like the documentation does not match the code.

**Comment by rmelick-vida** [comment]
I also noticed that my synchronizer seemed to be defaulting the ImpressionsPostRate to 300 seconds, instead of the documented 60, when I checked the `/admin/userConfig` endpoint

**Comment by chillaq** [comment]
Hi @rmelick-vida, Thanks for the info, that is correct, the 60 second minimum was introduced if ImpressionMode parameter is set to OPTIMIZED, if the ImpressionMode is set to DEBUG, it will allow lower than 60.

We will update the Runbook.

**Comment by chillaq** [comment]
Hi @rmelick-vida regarding the ImpressionsPostRate default value, the latest Synchronizer build is 60, can you confirm you got the latest build?

**Comment by rmelick-vida** [comment]
Hi @chillaq , I was running 4.0.2, perhaps that explains the difference?  I was able to successfully configure it down to 60, which meets my needs right now.
