### ISSUE TITLE
v5.0: Breaking change: api-key becomes apikey

### ISSUE THREAD

**Issue by dragonpaw** [splitio/split-synchronizer#164]
in versions through 4.x, the environment variable for the api key was 'SPLIT_SYNC_API_KEY' but apparently it changes to 'SPLIT_SYNC_APIKEY' in 5.x.

The docs here on github still all reference the old name.

But running the new split-synchronizer docker container 5.0.0 with the old value gives:
Split-Sync - ERROR - 2021/11/22 19:36:52 main.go:72: Failed to initialize the split sync:  initialization error: error parsing client key from provided apikey: apikey too short

If I rename the variable to SPLIT_SYNC_APIKEY then 5.0.0 starts up fine.

**Comment by mredolatti** [comment]
Hi @dragonpaw . My apologies for the inconveniences caused. v5.0.0 indeed breaks backwards compatibility with previous versions with regards to CLI arguments, enviroment variables, and proxy usage (among other stuff). Official docs will be published soon with all supported options and as well as other changes in behaviour.

Meanwhile i've updated the snippets in the README. We'll let you know as soon as the official docs are updated.

Once again sorry for the issues caused.
Martín.
