### ISSUE TITLE
Upgrade version to 5.0.2 docker image error

### ISSUE THREAD

**Issue by hvuhsg** [splitio/split-synchronizer#174]
We wanted to upgrade from 4.0.2 to 5.0.2 (using djengo_split and split_client sdk)
On local machine the only change needed is updating the version and changing the ENV VAR from SPLIT_SYNC_API_KEY -> SPLIT_SYNC_APIKEY.
And it works!

On AWS the same change result this errors. (the API KEY didn't change)

```
Split-Sync - ERROR - 2022/02/09 10:23:38 client.go:109: GET method: [https://auth.split.io/api/auth] Status Code: 400 - 400 Bad Request
Split-Sync - ERROR - 2022/02/09 10:23:38 auth.go:29: Error while authenticating for streaming 400 Bad Request
Split-Sync - ERROR - 2022/02/09 10:23:38 manager.go:200: non retryable error in streaming subsystem. Switching to polling until next SDK initialization
Split-Sync - ERROR - 2022/02/09 10:26:38 threshold.go:110: counter 'Segments' has timed out with tolerance=180s
Split-Sync - INFO - 2022/02/09 10:50:47 runtime.go:98:
* Starting graceful shutdown
Split-Sync - INFO - 2022/02/09 10:50:47 runtime.go:99:  * Waiting goroutines stop
Split-Sync - INFO - 2022/02/09 10:50:47 manager.go:169: Stopping all synchronization tasks
Split-Sync - INFO - 2022/02/09 10:50:47 runtime.go:111:  * Shutdown complete - see you soon!

```

Can you help me please?

**Comment by mredolatti** [comment]
Hey @hvuhsg sorry to hear you're having issues

Would you mind going through our official support on out site? We would need to know what your environment variables variables look like on the container? Can you make sure that you're using an sdk type Apikey? (not an admin or shared one)

Thanks,
Martín

**Comment by chillaq** [comment]
Hi @hvuhsg, Also, please enable verbose log, repro the issue and provide the full log.

Thanks

**Comment by hvuhsg** [comment]
I have created new api key with type server-side (client-side before) and it seem to work.

**Comment by mredolatti** [comment]
Glad to hear that, let us know if we can be of further help.
