### ISSUE TITLE
Proxy and Redis Cache

### ISSUE THREAD

**Issue by crenus** [splitio/split-synchronizer#186]
I see the latest versions that proxy mode was split out. Does Synchronizer currently support both redis and proxy? 
My ask is instead of having an sdk connect directly to redis, I would like to have the sdk connect to synchronizer which then fetches from redis as opposed to split cloud.
Is this something that can be done currently?

**Comment by chillaq** [comment]
Hi @crenus , The current architecture when using redis storage, SDK connect on to redis only to fetch the split information, and writes the impressions back to redis. The Synchronizer will sync redis with Split cloud, and post the impressions/events created in redis to split cloud.

SDKs can connect to Split Proxy which will relay all requests to Split cloud, we don't support redis in such setup.

Split proxy is separated from synchronizer now, you can download each separately from our help page.

Thanks
