### ISSUE TITLE
Unable to pass a username to Redis config

### ISSUE THREAD

**Issue by meriouma** [splitio/split-synchronizer#200]
I've looked at the available environment variables, and we can only provide those :
```
SPLIT_SYNC_REDIS_HOST
SPLIT_SYNC_REDIS_PORT
SPLIT_SYNC_REDIS_DB
SPLIT_SYNC_REDIS_PASS
```

We need to be able to specify a username as we want to use ACL in Redis 6.

**Comment by agustinona** [comment]
Hi @meriouma,

Our engineering team is evaluating this feature request. Expect it to be included in a future release.

**Comment by matthewbyrne** [comment]
Also looking for this feature.

**Comment by meriouma** [comment]
Thank you! I'll try it ASAP.

**Comment by meriouma** [comment]
Everything works fine, thank you!
