### ISSUE TITLE
Feature Idea - Prometheus metrics

### ISSUE THREAD

**Issue by alt-dima** [splitio/split-synchronizer#232]
It will be very good to expose metrics from `/admin/dashboard/stats` (and the best from other monitoring endpoints too) on another endpoint (`/metrics`) in prometheus format.

Then prometheus server can scrape those metrics and with Grafana create dashboard and alerts.

**Comment by agustinona** [comment]
Hi @alt-dima thank you for the suggestion! 

I've submitted this as a feature request for evaluation by our product team. You can check this repo's [changelog](https://github.com/splitio/split-synchronizer/blob/master/CHANGES.txt) to watch for this feature in case it's included in a future release.

**Comment by rtrive** [comment]
hey! any update on this feature request? I didn't find anything on the changelog
