### ISSUE TITLE
[SCALING] Deployment with multiple pod behavior

### ISSUE THREAD

**Issue by rtrive** [splitio/split-synchronizer#248]
Recently, we have been implementing split synchronizer within our K8s environment, and we have encountered a scenario where we need some clarification.

Could you please provide some insights on how the split synchronizer works when there are multiple instances running concurrently in a K8s deployment? Specifically, we are interested in understanding the following:

1. How does the split synchronizer handle synchronization conflicts when multiple instances attempt to modify the same resource simultaneously (e.g., updating redis key)?
2. Are there any limitations or known issues related to deploying multiple instances of the split synchronizer within a K8s cluster?

Thanks!

**Comment by hbqdev** [comment]
Hi @rtrive 

The Synchronizer is not designed share multiple replicas with only 1 redis instance. Unfortunately if you want to scale, you will need to do so in Synchronizer + Redis pair.

Regards
