### ISSUE TITLE
The /info/config path leaks the Redis password

### ISSUE THREAD

**Issue by gdurandvadas** [splitio/split-synchronizer#253]
As can be seen on the image, the path /info/config shows the redis password. The `apikey` is sanitised.

<img width="559" alt="info" src="https://github.com/splitio/split-synchronizer/assets/15437208/f2a35279-8512-447c-98dc-b1cbb3b563a5">

**Comment by mmelograno** [comment]
Hi @gdurandvadas, the latest version `5.5.1` deployed solves the issue.

I'll be closing this issue for now, but feel free to reopen if necessary.

Thank you for reaching out.
Matias.
