### ISSUE TITLE
BC Break found between 4.0.0 and 5.8.1

### ISSUE THREAD

**Issue by zbigniew-malcherczyk-tg** [splitio/split-synchronizer#282]
Somewhere between these veersions the BC break SPLIT_SYNC_API_KEY → SPLIT_SYNC_APIKEY was made and the changelog does not mention it.

**Comment by agustinona** [comment]
Hi @zbigniew-malcherczyk-tg ,

You are correct, this breaking change was introduced in version 5.0.0. Here's the corresponding changelog entry:

> 5.0.0 (Nov 1, 2021)
> - BREAKING CHANGE: Config options cleanup

It was unfortunately not practical to list every changed configuration parameter name, but the official documentation always lists the currently accepted configuration parameters: https://help.split.io/hc/en-us/articles/360019686092-Split-Synchronizer#cli-configuration-options-and-its-equivalents-in-json--environment-variables
