### ISSUE TITLE
Feature suggestion: Modify the shutdown message

### ISSUE THREAD

**Issue by guidodobboletta** [splitio/split-synchronizer#38]
There's two features that would be nice to have. 

First one would be to customize the shutdown message. Right now we're getting this `*[IMPORTANT]* @here Shutting Split-Sync down - see you soon!` in Slack and a lot of people are being alerted by `@here` which is not something we want.

Second feature that would be nice to have is to have slack alerts for application startup, right now we only get alerts when it shuts down but not when it starts up.

**Comment by mredolatti** [comment]
Hello @guidodobboletta , thank you very much for your feedback. We will definitely keep this in mind for our next release. I'll keep this issue open so we can let you know when it's done.

**Comment by patricioe** [comment]
Hi,

We already addressed your request in the current (latest) release. And we went ahead and filed your request. I'm going to go ahead and close this issue for now.

Please don't hesitate to reach out if you have more suggestions or feedback.

Thank you.

**Comment by patricioe** [comment]
I spoke too soon. I'll keep this issue open until we release the final version.

**Comment by patricioe** [comment]
Alright, version 2.4.1 addresses the removal of the @here during shutdown.

**Comment by mmelograno** [comment]
Hi @guidodobboletta, we've added a message when Split Sync starts in slack in version `2.5.0`.

Thank you very much for your feedback.

Cheers,
Matias
