### ISSUE TITLE
Support Redis Cluster

### ISSUE THREAD

**Issue by bryanspears** [splitio/split-synchronizer#39]
Your PHP SDK supports redis cluster, but it appears the synchronizer does not.
https://github.com/splitio/split-synchronizer/blob/master/splitio/storage/redis/client.go#L32

Needs to use NewClusterClient
https://godoc.org/github.com/go-redis/redis#NewClusterClient

**Comment by mredolatti** [comment]
Hi @bryanspears , thank you very much for the feedback. We'll do our best to have redis-cluster support in the next release of the split-sync which should be out soon.

**Comment by scottkrohn** [comment]
@mredolatti Do you have an approximate timeframe for the next release that includes cluster support?

**Comment by mmelograno** [comment]
Hi @bryanspears, @scottkrohn. Redis Cluster support was added on the last release (`1.8.0`). Thanks for the feedback provided.
