### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by ryanrapp** [splitio/split-synchronizer#59]
We need to connect to Redis over a TLS connection. This is a supported option in the Redis client library `github.com/go-redis/redis` that Synchronizer uses, but this isn't exposed as a configuration paramter.

My suggestion would be to add it to the `SPLIT_SYNC_ADVANCED_PARAMETERS` as `-redis-tls=true`.

See the PR I've created - #58

**Comment by mmelograno** [comment]
Hi @ryanrapp,

Thanks for your feedback. We will review it and we will be back soon.

Matias

**Comment by mmelograno** [comment]
Hi @ryanrapp,

We have added TLS Support in the last version of our Sync `2.4.0`. You could find the new parameters https://help.split.io/hc/en-us/articles/360019686092-Split-synchronizer#synchronizer-configuration under `Configure Redis` section.

Thanks,
Matias
